#+TITLE: cl-collider Installation Tutorial
#+OPTIONS: \n:t timestamp:nil

* 本文目标
配置 SuperCollider 的操作层 Common Lisp 语言环境。
具体表现为在 sbcl REPL 内可以使用 cl-collider 控制 SuperCollider 发声。
* 将会使用到的程序
- MSYS2
  - SuperCollider = [scsynth, sclang, scide, supernova]
  - Jack2
  - sbcl
  - git
- ocicl
  - cl-collider
* 具体的操作指南
** 安装 MSYS2
a. 访问 https://www.msys2.org/
b. 根据页面指引，安装 =x86_64= 也就是 64 位的 msys2 installer。
c. 安装好后，配置 Windows 环境变量，方法参见[fn:1]。
   需要注意的是，在配置好 Windows 环境变量后，运行 PowerShell 的终端中也是能够运 =pacman= 命令的。
d. 还是先在 UCRT64 shell 下更新 pacman 包仓库和本体。
#+BEGIN_SRC bash
  pacman -Syu
#+END_SRC
e. 按提示所说重启 UCRT64 终端。
** 通过 MSYS2 安装部分后续程序
a. 通过 pacman 命令安装程序。
   推荐用其他终端，MSYS2 的终端难以进行复制和粘贴操作。
#+BEGIN_SRC bash
  pacman -Su \
         mingw-w64-ucrt-x86_64-jack2 \
         mingw-w64-ucrt-x86_64-sbcl \
         mingw-w64-ucrt-x86_64-supercollider \
         git
#+END_SRC
** 编译 ocicl
更多请参见这个 [[https://github.com/ocicl/ocicl][github repo: ocicl]] 和它README里的 [[https://github.com/ocicl/ocicl?tab=readme-ov-file#installation][installation guide]].
Linux 或 Unix 平台可以使用包管理下载，请参考以上链接，Windows 平台需要自己编译：
a. 从源代码编译 ocicl，这是一个 common lisp 包管理程序。
#+BEGIN_SRC bash
  cd ~
  git clone https://github.com/ocicl/ocicl.git
  cd ocicl
  sbcl --load setup.lisp
#+END_SRC
b. ocicl.exe 将会出现在 =%UserProfile%\AppData\Local\ocicl\= 目录下。 
   一个典型的目录是 =C:\Users\Your-User-Name\AppData\Local\ocicl\bin= ，
   *需要* 将该含有 =ocicl.exe= 的文件夹路径添加到Windows系统环境变量里，方法参见脚注[fn:1]。
c. 在PowerShell终端下运行 =ocicl version= 后正常打印该程序的信息后，你就可以删除该源代码文件夹了。
** 使用 ocicl 安装 cl-collider
a. 切换到 PowerShell 终端下，执行：
#+BEGIN_SRC PowerShell
  ocicl setup
#+END_SRC
b. 将该命令打印出的内容粘贴到 =~/.sbclrc= 中。
c. 正式开始安装 cl-collider。执行：
#+BEGIN_SRC PowerShell
  ocicl --global install cl-collider
#+END_SRC
** 使用 sbcl REPL 运行 cl-collider
a. 终端中输入以下命令：
#+BEGIN_SRC bash
  sbcl
#+END_SRC
b. 进入 REPL，再依次执行如下 Common Lisp 语句，以启动 scsynth 服务器。
#+BEGIN_SRC lisp
  (asdf:load-system :cl-collider)
  (in-package :sc-user)
  (setf *sc-synth-program* "C:/msys64/ucrt64/bin/scsynth.exe")
  (setf *sc-plugin-paths* (list "C:/msys64/ucrt64/lib/SuperCollider/plugins/"))
  (setf *s* (make-external-server "localhost" :port 4444))
  (server-boot *s*)
#+END_SRC
c. 一个简单的发声测试语句。
#+BEGIN_SRC lisp
  (proxy :test-sound (sin-osc.ar 440 0 0.2))
  ;;stop playing
  (proxy :test-sound nil)
  ;;exit sbcl
  (in-package :cl-user)
  (exit)
#+END_SRC
d. 将以上 =b.= 部分的信息写入 =~/.sbclrc= 尾部，即可实现对cl-collider进行配置。
#+BEGIN_SRC lisp
  ;; In your ~/.sbclrc
  (defun my/cl-collider-boot ()
    ;; codes in "b."
    )
  ;; In REPL run this to quickly boot that.
  (my/cl-collider-boot)
#+END_SRC
* Footnotes
[fn:1] 如何配置 Windows 环境变量。
1. 按下 Windows 徽章键，搜索“系统环境变量”。
2. 弹出的卡片菜单里“高级”分页内，最下面“确认“按钮上方，点击该“编辑环境变量”按钮。
3. 我们需要编辑列表中 ”PATH“ 的值，选中列表的 ”PATH“，双击或点击”编辑按钮“打开完整列表。
   添加:
#+BEGIN_SRC plain-text
  C:\msys64\ucrt64\bin
  C:\msys64\mingw64\bin
  C:\Users\JohnDoe\AppData\Local\ocicl\bin
           ~~~~~~~
           ^Repalce this to your user name. 
#+END_SRC
